# Generated by Django 4.1.4 on 2023-01-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0002_alter_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_id',
        ),
    ]
