# Generated by Django 4.1.4 on 2023-01-05 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0004_remove_order_product_id_order_product_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
