# Generated by Django 4.1.4 on 2023-01-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0005_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
