# Generated by Django 4.1.4 on 2023-01-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0006_alter_order_price_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
