# Generated by Django 4.1.4 on 2023-01-06 00:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0010_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catlog.order'),
            preserve_default=False,
        ),
    ]
