# Generated by Django 4.1.4 on 2023-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0015_alter_order_product_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sell', models.IntegerField()),
            ],
        ),
    ]
